server:
  port: 8080
# spring
spring:
  datasource:
    url: jdbc:mysql://223.4.65.62:408/zhej_visual?characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useUnicode=true
    username: zjgovd
    password: 3OvuWd1_f32eH8SjU
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    expire: 1800
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 5
        max-wait: -1s
#mybatis mapper文件路径
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: top.moitoi.datacrawl.domain
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
    jdbc-type-for-null: 'null' # ''加单引号